#!/usr/bin/env python
# coding: utf-8

import argparse

REGISTERED='®'

parser = argparse.ArgumentParser(
        description='Convert source code for a Geant4 detector construction into a geometry that can be read by TRIPOLI-4'+REGISTERED+'.',
        epilog='Any unrecognized CLI options will be passed to the compiler.')

# arguments
parser.add_argument('-o', '--output', help='name of the file to generate', default='libG4Tripolizer.so')
parser.add_argument('-I', '--include', help='directories to search for include files (may be specified multiple times)', action='append')
parser.add_argument('-d', '--detector', help='name of the detector-construction class')
parser.add_argument('-p', '--parallel', help='name of a class defining a parallel geometry (may be specified multiple times; order matters)', action='append')
parser.add_argument('--', dest='remanining_flags', metavar='FLAG', nargs='*', help='pass all the remaining flags to the compiler')

# parse the arguments
args = parser.parse_args()

import detect_compiler

print detect_compiler.compiler_and_flags()
print args.include
